#pragma once
#include <string>

std::string weapon(short id) {
	switch (id) {
		case 1:
			return "deagle";
		case 2:
			return "dualies";
		case 3:
			return "fiveseven";
		case 4:
			return "glock";
		case 7:
			return "ak47";
		case 8:
			return "aug";
		case 9:
			return "awp";
		case 10:
			return "famas";
		case 11:
			return "g3sg1";
		case 13:
			return "galil";
		case 14:
			return "m249";
		case 16:
			return "m4a4";
		case 17:
			return "mac10";
		case 19:
			return "p90";
		case 23:
			return "mp5sd";
		case 24:
			return "ump45";
		case 25:
			return "xm1014";
		case 26:
			return "ppbizon";
		case 27:
			return "mag7";
		case 28:
			return "negev";
		case 29:
			return "sawedoff";
		case 30:
			return "tec9";
		case 31:
			return "taser";
		case 32:
			return "p2000";
		case 33:
			return "mp7";
		case 34:
			return "mp9";
		case 35:
			return "nova";
		case 36:
			return "p250";
		case 37:
			return "shield";
		case 38:
			return "scar20";
		case 39:
			return "sg556";
		case 40:
			return "scout";
		case 43:
			return "flash";
		case 44:
			return "grenade";
		case 45:
			return "smoke";
		case 46:
			return "molotov";
		case 47:
			return "decoy";
		case 48:
			return "incendiary";
		case 49:
			return "bomb";
		case 57:
			return "healthshot";
		case 60:
			return "m4a1s";
		case 61:
			return "usps";
		case 63:
			return "cz75";
		case 64:
			return "revolver";
		case 68:
			return "ta";
		case 69:
			return "fists";
		case 70:
			return "breach";
		case 72:
			return "tablet";
		case 74:
			return "melee";
		case 75:
			return "axe";
		case 76:
			return "hammer";
		case 78:
			return "spanner";
		case 80:
			return "knife";
		case 81:
			return "firebomb";
		case 82:
			return "diversion";
		case 83:
			return "frag";
		case 84:
			return "snowball";
		case 85:
			return "bumpmine";
		case -1:
			return "none";
		default:
			return "knife";
	}
}